networks:
  internal:

services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: sc_map
      POSTGRES_PASSWORD: sc_map
      POSTGRES_DB: sc_map
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sc_map -d sc_map']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      args:
        PUBLIC_GOOGLE_MAPS_API_KEY: ${PUBLIC_GOOGLE_MAPS_API_KEY}
        PUBLIC_DISCORD_CLIENT_ID: ${PUBLIC_DISCORD_CLIENT_ID}
    restart: unless-stopped

    expose:
      - '3000'

    networks:
      - internal

    depends_on:
      db:
        condition: service_healthy

    environment:
      SQL_URL: postgres://sc_map:sc_map@db:5432/sc_map
      ORIGIN: ${ORIGIN}
      PUBLIC_GOOGLE_MAPS_API_KEY: ${PUBLIC_GOOGLE_MAPS_API_KEY}
      SESSION_SECRET: ${SESSION_SECRET}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      DISCORD_GOATED_ROLE_ID: ${DISCORD_GOATED_ROLE_ID}

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}

    networks:
      - internal
    depends_on:
      - app
